org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true

mod_id=big_oceans
mod_name=Big Oceans
mod_version=0.1.0
mod_group=dev.bigoceans
mod_description=Makes Minecraft's oceans actually feel like oceans.
mod_license=MIT

minecraft_version=1.21.1
neoform_version=1.21.1-20240808.144430
fabric_loader_version=0.19.5
fabric_api_version=0.116.17+1.21.1
neoforge_version=21.1.252
