minecraft_version=1.21.5
neoform_version=1.21.5-20250325.162830
fabric_api_version=0.128.2+1.21.5
neoforge_version=21.5.98
fabric_minecraft_range=1.21.5
neoforge_minecraft_range=[1.21.5,1.21.6)
neoforge_range=[21.5,21.6)
jar_label=1.21.5
