plugins {
    id 'net.neoforged.moddev'
}

base.archivesName = "${mod_id}-neoforge"

def common = project(':common')

sourceSets.main {
    java.srcDir common.file('src/main/java')
    resources.srcDir common.file('src/main/resources')
}

neoForge {
    version = neoforge_version
    runs {
        server {
            server()
            gameDirectory = file('run/server')
            programArgument '--nogui'
        }
        client {
            client()
            gameDirectory = file('run/client')
            if (project.hasProperty('clientArgs')) project.clientArgs.split(' ').each { programArgument it }
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    def props = [version: version, mod_id: mod_id, mod_name: mod_name, mod_description: mod_description,
                 mod_license: mod_license, minecraft_version: minecraft_version, neoforge_version: neoforge_version]
    inputs.properties props
    filesMatching('META-INF/neoforge.mods.toml') { expand props }
}
